#!/bin/bash

vault secrets enable aws

vault write aws/config/root \
    access_key=AKIAJWVN5Z4FOFT7NLNAEXAMPLE \
    secret_key=R4nm063hgMVo4BTT5xOs5nHLeLXA6lar7ZJ3Nt0iEXAMPLE \
    region=eu-central-1
    
vault write aws/roles/deploy \
    role_arns=arn:aws:iam::361818425458:role/Assumed_role1\
    credential_type=assumed_role
    
vault write aws/sts/deploy ttl=60m
